### ISSUE TITLE
Capstone project two : Day 0

### ISSUE THREAD

**Issue by Chrissiku** [Chrissiku/capstone_project_two#22]
## Project Link
Link to the Github project: https://github.com/Chrissiku/capstone_project_two/projects/1

## Team members 👥 
This project will be completed by a team of 2 people listed bellow
- Student A: @bruk19 
- Student B: @Chrissiku

**Comment by TedLivist** [comment]
## STATUS: INVALID CODE REVIEW REQUEST 🛑 🛑

Hi @Chrissiku and @bruk19,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

### You are required to submit the link to your Kanban board itself, whereas you submitted the link your repo

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the Issue thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Issue for re-reviews. You should use the same Issue submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._
